branch: main
repositoryUrl: "https://github.com/rescript-ui/rescript-chakra.git"
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: next
    prerelease: true
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"
