// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(props) {
  return React.createElement("div", undefined, props.msg, React.createElement("a", {
                  href: props.href,
                  target: "_blank"
                }, "`rescript-chakra/examples`"));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "You can find examples here",
                href: "https://github.com/ri7nz/rescript-chakra/tree/main/examples"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
